<?php

/**
 * config.inc of Nesys_at_Home.
 * User: Al_Bundy@breakingcades.info
 * Date: 8/24/2017
 * Time: 10:14 AM
 */

define('MYSQL_USERNAME', 'root');
define('MYSQL_PASSWORD', 'password');
define('MYSQL_HOSTNAME', 'localhost');
define('MYSQL_PORT', 3306);
define('MYSQL_SERVICE_NAME', 'XE');
define('RANKING_2110_DATABASE', 'nesys_hl2_2110_ranking');
define('RANKING_3032_CARD', 'nesys_hl2_3032_card');
define('RANKING_3032_DATABASE', '3nesys_hl2_032_ranking');
define('RANKING_2110_CARD', 'nesys_hl2_2110_card');
define('CERT_DATABASE', 'nesys_cert');
define('NESYS_DATABASE', 'nesys');
